### ISSUE TITLE
Please provision existing official Ubuntu translation teams for your work

### ISSUE THREAD

**Issue by fitojb** [canonical/ubuntu-desktop-provision#173]
I am ~fito on Weblate, and ~fitojb on Launchpad. I am a member of the official Ubuntu translators, but I haven't contributed on Weblate because honestly anyone can sabotage my work. Fix the permissions or migrate to your own instance. We warned Canonical years ago on Discourse.

**Comment by tim-hm** [comment]
Hi @fitojb thanks for raising the issue. We'll be continuing our investigation this week and although I'm not sure at this moment what the way forward will be, we will absolutely be tightening things up.
