### ISSUE TITLE
Remove "post install" pages from ubuntu_bootstrap

### ISSUE THREAD

**Issue by d-loose** [canonical/ubuntu-desktop-provision#199]
In the new provisioning flow user creation, active directory configuration, setting timezone and theme are supposed to be done on first boot rather than during the installation process, so we should remove those pages from `ubuntu_bootstrap`.

**Comment by spydon** [comment]
So on first boot here means within `ubuntu_init` right?

**Comment by d-loose** [comment]
Eventually - yes. If we remove those now gnome-initial-setup should be able to take care of that until we have ubuntu-desktop-init in place.
