### ISSUE TITLE
Launch user session after first boot initialization

### ISSUE THREAD

**Issue by d-loose** [canonical/ubuntu-desktop-provision#297]
After completing the first boot initialization, in which the first user account is created, we need to log in the new user and take them to the desktop.
Core desktop is currently doing this using [this](https://github.com/canonical/ubuntu-desktop-provision/pull/144/files#diff-29ff8861b552ad440711b934de53ffcf5c5668baa231cbd5d3aa0d1ca2bccb4a) bit of unmerged code. However, I'd propose to move this logic into `provd`, so that the UI can simply call something like a `LaunchUserSession()` method on the backend.

A big question that arises here is how this can be kept general enough so that it also works for non-GNOME based flavors. Would `provd` need to detect the desktop environment and then act accordingly?

**Comment by spydon** [comment]
Maybe for other DMs we could just restart their service?
I guess the only other option is to write similar classes as `gdm_service.dart` for all DMs we want to support, if they even support doing the same operations. Which other DMs do we want to support? 
LightDM, SDDM (is Kubuntu still using that?) and LXDM?

**Comment by d-loose** [comment]
> Maybe for other DMs we could just restart their service?

That could definitely be a backup solution. Of course it'd be nicer to directly transition to the desktop instead of having to go through the login screen.

> I guess the only other option is to write similar classes as `gdm_service.dart` for all DMs we want to support, if they even support doing the same operations.

Yes, I agree.

> Which other DMs do we want to support? LightDM, SDDM (is Kubuntu still using that?) and LXDM?

LightDM and SDDM should probably be cover most, if not all flavors that don't use GDM. I don't think LXDM is being used anymore (I think in most it has been replaced by LightDM.

**Comment by spydon** [comment]
> I don't think LXDM is being used anymore

I thought Lubuntu was using it, but they are apparently using SDDM.
