### ISSUE TITLE
'All windows' preview in taskbar is off center.

### ISSUE THREAD

**Issue by BrancuAlexandru** [canonical/ubuntu-desktop-provision#394]
![Screenshot from 2024-02-07 12-32-58](https://github.com/canonical/ubuntu-desktop-provision/assets/92156286/09f6a442-f25d-4ba0-a07d-ed7da57a6b79)

**Comment by d-loose** [comment]
Either I'm missing something or this is completely unrelated to this project. Please clarify and re-open if I'm mistaken.
