### ISSUE TITLE
Manual partitioning does not allow encryption or LVM

### ISSUE THREAD

**Issue by nbuechner** [canonical/ubuntu-desktop-provision#417]
Steps to reproduce:

- Boot the ISO
- Begin the installation, selecting "Something else" when asked how to install Ubuntu.
- At the manual partitioning screen, attempt to create any kind of LUKS installation.

Expected result: There should be some option to create LUKS partitions or an LVM group that can contain a LUKS partition, ideally with the ability to select any supported filesystem to be installed within the LUKS partition.

Actual result: No encryption or LVM-related options exists for any filesystem.

Related issue: https://github.com/canonical/ubuntu-desktop-installer/issues/1770

( moved over from https://github.com/canonical/ubuntu-desktop-installer/issues/1353 )

**Comment by spydon** [comment]
Is there a launchpad issue for this? These type of issues are not tracked in this repository.

**Comment by d-loose** [comment]
https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2058511
