### ISSUE TITLE
Collection of UI issues

### ISSUE THREAD

**Issue by d-loose** [canonical/ubuntu-desktop-provision#495]
- [x] Remove back button on first page
- [x] Change title of accessibility page
- [x] Update copy on keyboard page
- [x] Review margins on network page
- [x] Update mascot on refresh page
- [x] Update copy on refresh page
- [x] Replace logo with mascot on try-or-install page
- [x] Update copy on try-or-install page
- [x] Select 'install' by default on try-or-install page
- [x] Change button label to 'close' when selecting 'try' on try-or-install page
- [x] Check alignment on try-or-install page
- [x] Update copy on autoinstall page
- [x] Check alignment and font size on autoinstall page
- [x] Update copy on source selection page
- [x] Check alignment on drivers/codecs page
- [x] Update copy on drivers/codecs page
- [x] Remove boxes on storage page, separate first two options
- [x] Remove release number on storage page (?)
- [x] Add 'experimental' badge to TPM option in advanced feature dialog
- [x] Implement new designs for guided resize and guided reformat pages
- [x] Implement new AD page desig
- [x] Implement error page design
- [x] Update copy on RST and bitlocker pages
- [x] Change to elevated button on RST and bitlocker pages
- [x] Interchange buttons on 'done' page
- [x] Update copy on 'done' page

**Comment by anasereijo** [comment]
remove back button

<img width="932" alt="Screenshot 2024-03-13 at 15 09 29" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/fca2e036-a2ed-40c6-975d-33cf5813e668">

**Comment by anasereijo** [comment]
<img width="951" alt="Screenshot 2024-03-13 at 15 12 08" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/b3552793-a141-4d0b-9850-41452713efa2">
change title to 'Accessibility'

**Comment by anasereijo** [comment]
<img width="601" alt="Screenshot 2024-03-13 at 15 14 30" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/9812af6e-b044-4f4a-b471-60c1a47858a0">

change to:
<img width="422" alt="Screenshot 2024-03-13 at 15 14 49" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/220f296f-98eb-4fd6-9e24-bea87c76c02b">

**Comment by anasereijo** [comment]
<img width="526" alt="Screenshot 2024-03-13 at 15 17 22" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/f89e34e6-3713-4fac-846a-db1eec680021">

**Comment by anasereijo** [comment]
<img width="908" alt="Screenshot 2024-03-13 at 15 18 57" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/e861c2f7-b947-4561-b60d-89e982ea15fd">
- update with new mascot
- update title + text
- update button label

**Comment by anasereijo** [comment]
<img width="960" alt="Screenshot 2024-03-13 at 15 22 57" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/9c7d0ba8-d3e7-4e10-962b-96d998f1432b">

- update title bar copy
- update copy/title
- update copy in the options
- replace logo with mascot
- when selecting the options, the 'next' button moves around
- when selecting 'try' the button label should read 'close' and not next
- have install selected by default
- align vertically
-

**Comment by anasereijo** [comment]
<img width="877" alt="Screenshot 2024-03-13 at 15 28 11" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/725100cf-5514-42fb-a7d9-88552e3c5d3d">
- update title bar copy
- make it vertically aligned
- when validating, the button should be disabled
- make font size match the next screen

**Comment by anasereijo** [comment]
<img width="1041" alt="Screenshot 2024-03-13 at 15 41 03" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/e97efd21-9980-4ee0-a50d-c5c287c2cb1a">

remove 'games'. should read like in figma

**Comment by anasereijo** [comment]
<img width="1023" alt="Screenshot 2024-03-13 at 15 41 49" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/7df340c7-bf2a-4f38-be24-d2b516544a03">

- remove scrollbar 
- update copy 
<img width="525" alt="Screenshot 2024-03-13 at 15 42 39" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/45ea1db9-299f-41d7-818e-d053b55f36dd">

**Comment by anasereijo** [comment]
<img width="623" alt="Screenshot 2024-03-13 at 15 47 43" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/adfb1232-572b-4963-b369-2e6efb23db59">
- try to remove the release number from the options
- separate the first two options
- delete boxes (check figma)

**Comment by anasereijo** [comment]
<img width="772" alt="Screenshot 2024-03-13 at 15 53 15" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/1958728c-75d4-4e5a-a1ba-f7f76105f725">
experimental badge missing from the last option

**Comment by anasereijo** [comment]
<img width="1070" alt="Screenshot 2024-03-13 at 16 00 50" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/7bb76a1e-8b9c-4388-b157-93acf61c90d9">
- make it similar to the one with the slider, but without the slider

**Comment by anasereijo** [comment]
<img width="1081" alt="Screenshot 2024-03-13 at 16 11 55" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/502cd233-fd8e-42e1-8cba-b05495e8b467">
update to the new design

**Comment by anasereijo** [comment]
<img width="1056" alt="Screenshot 2024-03-13 at 16 14 13" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/a0701948-273f-4fe1-a379-cc9f4371685e">

- change title bar copy
- weird background colour
- make the titles smaller (general, security, etc)

**Comment by anasereijo** [comment]
<img width="1031" alt="Screenshot 2024-03-13 at 16 18 56" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/3b636488-fb0b-43f9-9a4c-19c6758c6eea">

<img width="857" alt="Screenshot 2024-03-13 at 16 19 10" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/dcafcae1-33fd-4928-b347-fe92c1cb24fe">

**Comment by anasereijo** [comment]
<img width="1046" alt="Screenshot 2024-03-13 at 16 23 29" src="https://github.com/canonical/ubuntu-desktop-provision/assets/36884067/f205df8b-543e-43b8-a6cd-cf59d4ed644f">


- button should be primary
- update the copy

**Comment by spydon** [comment]
I guess we can close this one now, since all the boxes are checked!

**Comment by wathika-eng** [comment]
In the Ubuntu 24/25 installer, the Next button doesn’t change color when a choice is made. It would be more user-friendly if it would become active with a noticeable color change (like green) once a selection is made, so users can clearly see they can proceed. Can this be considered as a UI/UX improvement?

<img width="1012" height="732" alt="Image" src="https://github.com/user-attachments/assets/6980ee8d-ca9e-420e-9d84-947f84ff66f7" />

<img width="800" height="496" alt="Image" src="https://github.com/user-attachments/assets/09279475-a3b6-4885-bbe5-d0d7b1589e2d" />
