### ISSUE TITLE
FDE Installation will lead the OS unbootable.

### ISSUE THREAD

**Issue by alinourzad** [canonical/ubuntu-desktop-provision#577]
> Please report any bugs related to Ubuntu Desktop Provision on [Launchpad](https://bugs.launchpad.net/ubuntu-desktop-provision). We use the GitHub issue tracker only for issues related to the development of Ubuntu Desktop Provision itself

I was doing some testing for desktop provisioning for our company, and I was playing with FDE. Installed operating system using the interactive installation, when select LVM on partition manager, it works fine, but if I select LVM + encryption, the system will reboot into busy box initramfs. 
I have not digged into it yet because: 
1. Lack of knowledge.
2. it's a daily ISO and I thought it's going to change.

PS. Don't know if this is a bug yet. So no bug report created.

**Comment by daniel0076** [comment]
Probably related:
https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2058147

**Comment by spydon** [comment]
Closing this since it's a bug that belongs on LP
