### ISSUE TITLE
Help Improve Ubuntu error

### ISSUE THREAD

**Issue by henrycoggillcnc** [canonical/ubuntu-desktop-provision#606]
Not sure if this is the right place for this...

Upon installing Noble (https://cdimage.ubuntu.com/daily-live/current/noble-desktop-amd64.iso  09/04/2024), on first boot we are presented with the onboarding screens. One of these is about reporting data: "Help Improve Ubuntu".

I selected No to not share data with the Ubuntu team. The UI froze with a spinning cursor, until I was presented with an error message:
"Failed to send report decline: data were not delivered successfully to metrics server, saving for a later automated report: couldn't send post http request: Post "https://metrics.ubuntu.com/ubuntu/desktop/24.04": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

Problem #1: why is the UI blocking on a network request? This should be a background task or thread.

Problem #2: why is a report being made to our servers when I selected the option to not make a report to the servers?

![help_ubuntu_error](https://github.com/canonical/ubuntu-desktop-provision/assets/104218749/411baf92-39c2-430c-849c-f1aaa4bb0947)

**Comment by d-loose** [comment]
The screenshot is showing gnome-initial-setup. Ubuntu-specific bugs for that are tracked [here](https://bugs.launchpad.net/ubuntu/+source/gnome-initial-setup).

**Comment by henrycoggillcnc** [comment]
Ok, thanks! I will move it :)
