### ISSUE TITLE
Installing with hardware backed encryption leads to prompt for recovery key at first boot

### ISSUE THREAD

**Issue by ZVNexus** [canonical/ubuntu-desktop-provision#633]
Installed the Ubuntu 24.04 daily ISO on the following hardware:
Host: ROG CROSSHAIR X670E HERO
CPU: AMD Ryzen 9 7950X
GPU: AMD Radeon RX 7900 XTX

Running into an issue where if I install with hardware backed encryption, it leads to being prompted for the recovery key on first boot. Also `sudo snap recovery --show keys` doesn't return anything in terminal once the installation is done.

Attached the installer logs below:

[installer-logs.zip](https://github.com/canonical/ubuntu-desktop-provision/files/14949928/installer-logs.zip)

**Comment by ZVNexus** [comment]
Also able to reproduce this on my Dell XPS 9530 15".

**Comment by d-loose** [comment]
Thanks for your report! Could you please file a bug on [Launchpad](https://bugs.launchpad.net/ubuntu-desktop-provision) as mentioned [here](https://github.com/canonical/ubuntu-desktop-provision#bugs)?

**Comment by ZVNexus** [comment]
I already have a bug report on Launchpad (https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2058147), but I figured I'd report here as well since the Discourse 24.04 beta thread said to report issues with ubuntu-desktop-provision directly on the GitHub page and wanted to cover all bases.

Was unsure if Launchpad was the correct place to file bugs for this repository since I haven't see any activity on the bug report from Canonical for the past month, and the official release is scheduled to come out in less than 2 weeks and this is a bug that prevents the user from even getting to the login screen after first install.

**Comment by d-loose** [comment]
Thanks, let's continue this on launchpad then, I'll look into it next week!

The bug tracker situation was a bit confusing, I've [replied](https://discourse.ubuntu.com/t/ubuntu-24-04-lts-beta-testing/44040/15) on discourse.
