### ISSUE TITLE
EFI entry in boot menu shows as "UEFI OS" instead of "Ubuntu" when using hardware backed encryption

### ISSUE THREAD

**Issue by ZVNexus** [canonical/ubuntu-desktop-provision#634]
Installed the Ubuntu 24.04 daily ISO on the following hardware:
Host: ROG CROSSHAIR X670E HERO
CPU: AMD Ryzen 9 7950X
GPU: AMD Radeon RX 7900 XTX

Attached the installer logs below:

[installer-logs.zip](https://github.com/canonical/ubuntu-desktop-provision/files/14949928/installer-logs.zip)

**Comment by d-loose** [comment]
Thanks for your report! Could you please file a bug on [Launchpad](https://bugs.launchpad.net/ubuntu-desktop-provision) as mentioned [here](https://github.com/canonical/ubuntu-desktop-provision#bugs)?

**Comment by ZVNexus** [comment]
https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2061161
