### ISSUE TITLE
Ubuntu 24.04 beta. Segmentation fault, mdadm --scan 

### ISSUE THREAD

**Issue by linuxandos2** [canonical/ubuntu-desktop-provision#660]
installation of ubuntu 22.04 on system.
System has 2 fake-raids one is raid 1 on 2 1TB ssd's; the other is raid 5 on 6 18TB drives.
The raid's were created on a gentoo system on another partition on the raid 1 array.
During installation the raid arrays were not detected.
After installation on a non-raid nvme partition the raid arrays were not detected.
Installed mdadm.
Running mdadm --scan seg-faults.

What info can be provided to debug?
Thanks,
Marc.

**Comment by spydon** [comment]
Hi, this is not the right place to report bugs like this (like it said in the text that you removed before writing the issue).
For this question I would probably recommend [AskUbuntu](https://askubuntu.com), I don't know which issue tracker it could go on at least.
