### ISSUE TITLE
Add "Vanilla Console" option in Ubuntu Desktop Installer 

### ISSUE THREAD

**Issue by ConLenov** [canonical/ubuntu-desktop-provision#752]
I want to add the “Vanilla Console” option to the Ubuntu installer. I don't know if I can do this feature. "Vanilla Console" - option in the Ubuntu installer that installs a super-minimal Ubuntu (just the Linux kernel and the required libraries).
Option for Ubuntu users who want to install LabWC or vanilla gnome. 
![ubuntu](https://github.com/canonical/ubuntu-desktop-provision/assets/56037506/32a2aeb2-b009-4b98-a0d9-020c4aa05e15)

**Comment by spydon** [comment]
These options are not static and not configured in this repo, they come from subiquity's source API. You can just configure it from there if you're planning to use the installer in a flavor distro.
