### ISSUE TITLE
subiquity submodule update

### ISSUE THREAD

**Issue by ozgur-as** [canonical/ubuntu-desktop-provision#753]
hello,

due to a bug in subiquity, netbooting the 24.04 desktop iso with an autoinstall config results in a crash. (https://bugs.launchpad.net/subiquity/+bug/2062988)

it's fixed in subiquity, but injecting the subiquity snap into the iso does not fix the problem since the file (/snap/ubuntu-desktop-bootstrap/171/bin/subiquity/subiquity/cmd/server.py) is from the ubuntu-desktop-bootstrap snap. 

snappacking the current ci/bootstrap branch also results with the old server.py file since the repo is pointing to the old commit of the subiquity repo.

can you update the subiquity submodule to point to a commit newer than the pushed fix (https://github.com/canonical/subiquity/commit/eb155c363c73c922954fe613cdcf16de29042ad9) ?

thanks in advance.

**Comment by dbungert** [comment]
and once a stable snap of `ubuntu-desktop-bootstrap` is available with that fix, it should show up as well in [daily builds](https://cdimage.ubuntu.com/noble/daily-live/)

**Comment by ozgur-as** [comment]
i understand, thank you.

until then, would cloning and updating the submodule of ci/bootstrap and then going for "snapcraft pack ..." and injecting it into the iso would work? or during packing and compiling will snapcraft pull subiquity from the online repo and not result in an updated iso?

**Comment by d-loose** [comment]
If you update the subquity submodule on `ci/bootstrap`, you'll need to also create a commit with that change since the snapcraft.yaml uses `source-type: git`. You should also make sure that the `source-commit`s for subiquity's dependencies in the snapcraft.yaml match those from the submodule - the `ci/subiquity_integration` script can check for a mismatch, and `scripts/update-subiquity-deps` can be used to automatically update the snapcraft.yaml in case they aren't aligned.
After that you should be able to simply run `snapcraft` and obtain a snap that you can inject into the iso :)

**Comment by d-loose** [comment]
Fixed by #763

**Comment by DavidBoman** [comment]
> and once a stable snap of `ubuntu-desktop-bootstrap` is available with that fix, it should show up as well in [daily builds](https://cdimage.ubuntu.com/noble/daily-live/)

@dbungert : Where can I follow the progress of this? I'm having trouble finding the repo/issue-tracker for ubuntu-desktop-bootstrap.

**Comment by dbungert** [comment]
@DavidBoman - ubuntu-desktop-bootstrap is one of several pieces of software produced from this repo, so you're in the right place (though it looks like many bugs should be going to launchpad instead).  The bugs statement for this repo can be found at https://github.com/canonical/ubuntu-desktop-provision?tab=readme-ov-file#bugs 

Progress of this - I don't own the ubuntu-desktop-bootstrap snap, so I will generally turn that question over to others for further details, but at the moment the patched version is available on the snap candidate channel and promotion to stable would need to happen from there before it shows up in the ISO dailies.

**Comment by DavidBoman** [comment]
@dbungert : Thanks for the explanation! I'm a newbie when it comes to snap, so I'm still trying to wrap my head around the whole ecosystem.

**Comment by Chris-Peterson444** [comment]
I was able to download the 205 revision of ubuntu-desktop-bootstrap, inject it into the release desktop ISO, and perform a successful netboot install without running into the bug.

**Comment by DavidBoman** [comment]
I just verified that this is fixed in the latest pending version (2024-16-12) of the iso:

https://cdimage.ubuntu.com/noble/daily-live/pending/
