### ISSUE TITLE
Versions on snapstore possibly out of sync?

### ISSUE THREAD

**Issue by samuelallan72** [canonical/ubuntu-desktop-provision#759]
The versions in the snapcraft.yaml files is pulled from git, but the version on snapstore for ubuntu-desktop-provision shows 0+git.HASH , suggesting it was calculated on a shallow clone without older tags present?

![1717468735](https://github.com/canonical/ubuntu-desktop-provision/assets/9714796/c824966b-f5e0-4423-b357-fa1cce936756)

**Comment by spydon** [comment]
I think this is due to the fact that we need to build each app from a branch, since we have multiple apps in this repo.

**Comment by ozgur-as** [comment]
like @spydon said, ubuntu-desktop-bootstrap is built from the ci/bootstrap branch where the commits listed in the snapstore matches the commits.

https://github.com/canonical/ubuntu-desktop-provision/commits/ci/bootstrap/

**Comment by d-loose** [comment]
Related discussion: https://github.com/canonical/ubuntu-desktop-provision/pull/452#discussion_r1498875175

We're planning on simplifying this to resolve some of the issues mentioned in that discussion.
