### ISSUE TITLE
Black screen on old GPUs Nvidia

### ISSUE THREAD

**Issue by johnnynunez** [canonical/ubuntu-desktop-provision#780]
Installer doesn't appear if I use old Nvidia GPU as GTX Titan

**Comment by d-loose** [comment]
Thanks for the report - please consider filing an issue in the [bug tracker](https://bugs.launchpad.net/ubuntu-desktop-provision/) as mentioned in the [README](https://github.com/canonical/ubuntu-desktop-provision?tab=readme-ov-file#bugs).
This might be related to [lp:2061118](https://bugs.launchpad.net/gtk/+bug/2061118).
