### ISSUE TITLE
FIX: ubuntu installer doesnt work with some specific chars

### ISSUE THREAD

**Issue by ethicnology** [canonical/ubuntu-desktop-provision#831]
On Ubuntu 24.04, I attempted various password combinations, both with and without special characters, but the password I entered during installation didn't work on the installed OS.

I specifically tried using the character 'ù' but couldn’t log in after the installation.

To work around this installer bug, use a simple password during installation, and then change it to a more complex one afterward.

**Comment by d-loose** [comment]
Ok, got a bit nerd-sniped by this: the problem is that Dart uses UTF-16 encoding for strings and the [`crypt.dart`](https://pub.dev/packages/crypt) used here iterates over the UTF-16 code units of the password, while ubuntu is probably expecting UTF-8 during login.

A simple fix would be:

```diff
diff --git a/packages/ubuntu_bootstrap/lib/services/identity_service.dart b/packages/ubuntu_bootstrap/lib/services/identity_service.dart
index ff99d7ee9..f57e300d7 100644
--- a/packages/ubuntu_bootstrap/lib/services/identity_service.dart
+++ b/packages/ubuntu_bootstrap/lib/services/identity_service.dart
@@ -1,3 +1,5 @@
+import 'dart:convert';
+
 import 'package:crypt/crypt.dart';
 import 'package:meta/meta.dart';
 import 'package:subiquity_client/subiquity_client.dart';
@@ -37,7 +39,9 @@ class SubiquityIdentityService implements IdentityService {
       IdentityData(
         realname: identity.realname,
         username: identity.username,
-        cryptedPassword: Crypt.sha512(identity.password).toString(),
+        cryptedPassword:
+            Crypt.sha512(String.fromCharCodes(utf8.encode(identity.password)))
+                .toString(),
         hostname: identity.hostname,
       ),
     );
```

although it feels a bit hacky.
